version: "3.7"
services:
  # Homer
  homer:
    image: b4bz/homer:${HOMER_VERSION}
    hostname: ${HOSTNAME}
    container_name: homer
    restart: unless-stopped
    volumes:
      - ./homer-config.yml:/www/assets/config.yml
      - ./dashboard-icons:/www/assets-ext/
      - ./mintyclouds-logo.png:/www/assets/mintyclouds-logo.png
    environment:
      - UID=1000
      - GID=1000
      - TZ=Europe/Moscow
    ports:
      - ${HOMER_WEB_PORT}:8080


  # Wiki.js
  wikijs-postgresql:
    image: postgres:${WIKIJS_POSTGRES_VERSION}
    container_name: wikijs-postgresql
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: "${WIKIJS_POSTGRES_PASSWORD}"
      POSTGRES_USER: "${WIKIJS_POSTGRES_USER}"
      POSTGRES_DB: "${WIKIJS_POSTGRES_DB}"
    # ports:
    #   - "${WIKIJS_POSTGRES_PORT}:5432"
    volumes:
      - ${WIKIJS_POSTGRES_DATA_PATH}:/var/lib/postgresql/data

  wikijs:
    image: requarks/wiki:${WIKIJS_VERSION}
    hostname: ${HOSTNAME}
    container_name: wikijs
    restart: unless-stopped
    environment:
      DB_TYPE: postgres
      DB_HOST: wikijs-postgresql
      DB_PORT: 5432
      DB_USER: ${WIKIJS_POSTGRES_USER}
      DB_PASS: ${WIKIJS_POSTGRES_PASSWORD}
      DB_NAME: ${WIKIJS_POSTGRES_DB}
    ports:
      - ${WIKIJS_WEB_PORT}:3000
    depends_on:
      - wikijs-postgresql

  pigallery-nginx:
    image: nginx:${PIGALLERY_NGINX_VERSION}
    container_name: pigallery-nginx
    volumes:
      - ./pigallery-nginx.conf:/etc/nginx/nginx.conf
      - ${PIGALLERY_DATA_PATH}/nginx/error.log:/etc/nginx/error_log.log
      - ${PIGALLERY_DATA_PATH}/nginx/cache/:/etc/nginx/cache
    ports:
      - ${PIGALLERY_WEB_PORT}:3000
    restart: unless-stopped

  pigallery2:
    image: bpatrik/pigallery2:${PIGALLERY_VERSION}
    container_name: pigallery
    environment:
      - NODE_ENV=production # set to 'debug' for full debug logging
    volumes:
      - "${PIGALLERY_DATA_PATH}/pigallery2/config:/app/data/config"
      - "${PIGALLERY_DATA_PATH}/pigallery2/db-data:/app/data/db"
      - "${PIGALLERY_DATA_PATH}/pigallery2/tmp:/app/data/tmp"
      - "${PIGALLERY_GALLERY_PATH}:/app/data/images/gallery:ro"
      - "${PIGALLERY_MEDIA_PATH}/images:/app/data/images/media/images:ro"
      - "${PIGALLERY_MEDIA_PATH}/nsfw:/app/data/images/media/nsfw:ro"
    restart: always

