version: "3.7"
services:
  # Homer
  homer:
    image: b4bz/homer:${HOMER_VERSION}
    hostname: ${HOSTNAME}
    container_name: homer
    restart: unless-stopped
    volumes:
      - ./homer-config.yml:/www/assets/config.yml
      - ./dashboard-icons:/www/assets-ext/
      - ./mintyclouds-logo.png:/www/assets/mintyclouds-logo.png
    environment:
      - UID=1000
      - GID=1000
      - TZ=Europe/Moscow
    ports:
      - ${HOMER_WEB_PORT}:8080


  # Wiki.js
  wikijs-postgresql:
    image: postgres:${WIKIJS_POSTGRES_VERSION}
    container_name: wikijs-postgresql
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: "${WIKIJS_POSTGRES_PASSWORD}"
      POSTGRES_USER: "${WIKIJS_POSTGRES_USER}"
      POSTGRES_DB: "${WIKIJS_POSTGRES_DB}"
    # ports:
    #   - "${WIKIJS_POSTGRES_PORT}:5432"
    volumes:
      - ${WIKIJS_POSTGRES_DATA_PATH}:/var/lib/postgresql/data

  wikijs:
    image: requarks/wiki:${WIKIJS_VERSION}
    hostname: ${HOSTNAME}
    container_name: wikijs
    restart: unless-stopped
    environment:
      DB_TYPE: postgres
      DB_HOST: wikijs-postgresql
      DB_PORT: 5432
      DB_USER: ${WIKIJS_POSTGRES_USER}
      DB_PASS: ${WIKIJS_POSTGRES_PASSWORD}
      DB_NAME: ${WIKIJS_POSTGRES_DB}
    ports:
      - ${WIKIJS_WEB_PORT}:3000
    depends_on:
      - wikijs-postgresql
    
